USE master;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF DB_ID(N'autogara') IS NULL
BEGIN
    CREATE DATABASE autogara COLLATE Romanian_100_CI_AS;
END
ELSE IF CONVERT(NVARCHAR(128), DATABASEPROPERTYEX(N'autogara', 'Collation')) <> N'Romanian_100_CI_AS'
BEGIN
    RAISERROR (N'Baza de date autogara există deja, dar are alt collation decât Romanian_100_CI_AS.', 16, 1);
END
GO

ALTER DATABASE autogara SET RECOVERY SIMPLE;
GO

ALTER DATABASE autogara SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO

ALTER DATABASE autogara SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE autogara SET AUTO_UPDATE_STATISTICS ON;
GO
